//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class C__RefactorLog
        : Entity
    {
        [Column(Name = "OperationKey", DbType = "Guid", IsPrimaryKey = true, CanBeNull = false)]
        public System.Guid OperationKey { get; set; }
    }
}
