//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class Department
        : HierarchyEntity
    {
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public virtual int Id { get; set; }
        [Column(Name = "UniqueId", DbType = "Int32", CanBeNull = false)]
        public override int UniqueId { get; set; }
        [Column(Name = "Level", DbType = "Int16", Expression = "COMPUTED")]
        public override short Level { get { return base.Level; } set { } }
        [Column(Name = "Name", DbType = "String", CanBeNull = false)]
        public virtual string Name { get; set; }
        [Column(Name = "ParentId", DbType = "Int32", CanBeNull = false)]
        public virtual int ParentId { get; set; }
        [Column(Name = "Order", DbType = "Int32", CanBeNull = false)]
        public virtual int Order { get; set; }
        [Column(Name = "LastUpdateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdateTime;
    	public virtual System.DateTime LastUpdateTime 
    	{
    		get { return _lastUpdateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdateTime = value;
    			}
    		}
    	}
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public virtual bool IsActive { get; set; }
    }
}
