//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class EnterpriseNotice
        : Entity
    {
        public EnterpriseNotice()
        {
        }
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "Subject", DbType = "String", CanBeNull = false)]
        public string Subject { get; set; }
        [Column(Name = "AvatarPath", DbType = "String")]
        public string AvatarPath { get; set; }
        [Column(Name = "Summary", DbType = "String", CanBeNull = false)]
        public string Summary { get; set; }
        [Column(Name = "Context", DbType = "String", CanBeNull = false)]
        public string Context { get; set; }
        [Column(Name = "Category", DbType = "Byte", CanBeNull = false)]
        public byte Category { get; set; }
        [Column(Name = "NoticeType", DbType = "Byte", CanBeNull = false)]
        public byte NoticeType { get; set; }
        [Column(Name = "LastUpdateUser", DbType = "String", CanBeNull = false)]
        public string LastUpdateUser { get; set; }
        [Column(Name = "LastUpdateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdateTime;
    	public virtual System.DateTime LastUpdateTime 
    	{
    		get { return _lastUpdateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdateTime = value;
    			}
    		}
    	}
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public bool IsActive { get; set; }
    
        private ICollection<ConsEnterpriseNotice> _ConsEnterpriseNotice;
        public virtual ICollection<ConsEnterpriseNotice> ConsEnterpriseNotice
        {
            get { return this._ConsEnterpriseNotice ?? (this._ConsEnterpriseNotice = new HashSet<ConsEnterpriseNotice>()); }
            set { this._ConsEnterpriseNotice = value; }
        }
        private ICollection<DepartmentEnterpriseNotice> _DepartmentEnterpriseNotice;
        public virtual ICollection<DepartmentEnterpriseNotice> DepartmentEnterpriseNotice
        {
            get { return this._DepartmentEnterpriseNotice ?? (this._DepartmentEnterpriseNotice = new HashSet<DepartmentEnterpriseNotice>()); }
            set { this._DepartmentEnterpriseNotice = value; }
        }
        private ICollection<ProsEnterpriseNotice> _ProsEnterpriseNotice;
        public virtual ICollection<ProsEnterpriseNotice> ProsEnterpriseNotice
        {
            get { return this._ProsEnterpriseNotice ?? (this._ProsEnterpriseNotice = new HashSet<ProsEnterpriseNotice>()); }
            set { this._ProsEnterpriseNotice = value; }
        }
    }
}
