//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class ExamQuestion
        : Entity
    {
        public ExamQuestion()
        {
        }
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "ExamId", DbType = "Int32", CanBeNull = false)]
        public int ExamId { get; set; }
        [Column(Name = "No", DbType = "Int16", CanBeNull = false)]
        public short No { get; set; }
        [Column(Name = "Category", DbType = "Byte", CanBeNull = false)]
        public byte Category { get; set; }
        [Column(Name = "Question", DbType = "String", CanBeNull = false)]
        public string Question { get; set; }
        [Column(Name = "Image", DbType = "String")]
        public string Image { get; set; }
        [Column(Name = "CorrectAnswer", DbType = "String")]
        public string CorrectAnswer { get; set; }
        [Column(Name = "Score", DbType = "Double", CanBeNull = false)]
        public double Score { get; set; }
        [Column(Name = "LastUpdateUser", DbType = "String", CanBeNull = false)]
        public string LastUpdateUser { get; set; }
        [Column(Name = "LastUpdateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdateTime;
    	public virtual System.DateTime LastUpdateTime 
    	{
    		get { return _lastUpdateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdateTime = value;
    			}
    		}
    	}
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public bool IsActive { get; set; }
    
        public virtual Exam Exam { get; set; }
        private ICollection<ExamChoice> _ExamChoice;
        public virtual ICollection<ExamChoice> ExamChoice
        {
            get { return this._ExamChoice ?? (this._ExamChoice = new HashSet<ExamChoice>()); }
            set { this._ExamChoice = value; }
        }
        private ICollection<UserExamAnswer> _UserExamAnswer;
        public virtual ICollection<UserExamAnswer> UserExamAnswer
        {
            get { return this._UserExamAnswer ?? (this._UserExamAnswer = new HashSet<UserExamAnswer>()); }
            set { this._UserExamAnswer = value; }
        }
    }
}
