//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class Exam
        : Entity
    {
        public Exam()
        {
        }
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "Title", DbType = "String", CanBeNull = false)]
        public string Title { get; set; }
        [Column(Name = "Description", DbType = "String")]
        public string Description { get; set; }
        [Column(Name = "TotalScore", DbType = "Double", CanBeNull = false)]
        public double TotalScore { get; set; }
        [Column(Name = "PassingScore", DbType = "Double", CanBeNull = false)]
        public double PassingScore { get; set; }
        [Column(Name = "Status", DbType = "Byte", CanBeNull = false)]
        public byte Status { get; set; }
        [Column(Name = "GroupKey", DbType = "Guid")]
        public Nullable<System.Guid> GroupKey { get; set; }
        [Column(Name = "LastUpdateUser", DbType = "String", CanBeNull = false)]
        public string LastUpdateUser { get; set; }
        [Column(Name = "LastUpdateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdateTime;
    	public virtual System.DateTime LastUpdateTime 
    	{
    		get { return _lastUpdateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdateTime = value;
    			}
    		}
    	}
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public bool IsActive { get; set; }
    
        private ICollection<ExamQuestion> _ExamQuestion;
        public virtual ICollection<ExamQuestion> ExamQuestion
        {
            get { return this._ExamQuestion ?? (this._ExamQuestion = new HashSet<ExamQuestion>()); }
            set { this._ExamQuestion = value; }
        }
        private ICollection<TaskExam> _TaskExam;
        public virtual ICollection<TaskExam> TaskExam
        {
            get { return this._TaskExam ?? (this._TaskExam = new HashSet<TaskExam>()); }
            set { this._TaskExam = value; }
        }
    }
}
