//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class LearningFile
        : Entity
    {
        public LearningFile()
        {
        }
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "Subject", DbType = "String", CanBeNull = false)]
        public string Subject { get; set; }
        [Column(Name = "LastUpdateUser", DbType = "String", CanBeNull = false)]
        public string LastUpdateUser { get; set; }
        [Column(Name = "LastUpdateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdateTime;
    	public virtual System.DateTime LastUpdateTime 
    	{
    		get { return _lastUpdateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdateTime = value;
    			}
    		}
    	}
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public bool IsActive { get; set; }
        [Column(Name = "Description", DbType = "String")]
        public string Description { get; set; }
        [Column(Name = "FileType", DbType = "Byte", CanBeNull = false)]
        public byte FileType { get; set; }
        [Column(Name = "ChapterId", DbType = "Int32", CanBeNull = false)]
        public int ChapterId { get; set; }
        [Column(Name = "No", DbType = "Int32", CanBeNull = false)]
        public int No { get; set; }
        [Column(Name = "Content", DbType = "String", CanBeNull = false)]
        public string Content { get; set; }
    
        public virtual LearningChapter LearningChapter { get; set; }
        private ICollection<TaskExam> _TaskExam;
        public virtual ICollection<TaskExam> TaskExam
        {
            get { return this._TaskExam ?? (this._TaskExam = new HashSet<TaskExam>()); }
            set { this._TaskExam = value; }
        }
        private ICollection<TaskLearning> _TaskLearning;
        public virtual ICollection<TaskLearning> TaskLearning
        {
            get { return this._TaskLearning ?? (this._TaskLearning = new HashSet<TaskLearning>()); }
            set { this._TaskLearning = value; }
        }
    }
}
