//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class MessageDispatch
        : Entity
    {
        public MessageDispatch()
        {
        }
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "Subject", DbType = "String", CanBeNull = false)]
        public string Subject { get; set; }
        [Column(Name = "ToUsers", DbType = "String")]
        public string ToUsers { get; set; }
        [Column(Name = "ToDepts", DbType = "String")]
        public string ToDepts { get; set; }
        [Column(Name = "Priority", DbType = "Byte", CanBeNull = false)]
        public byte Priority { get; set; }
        [Column(Name = "MessageType", DbType = "Byte", CanBeNull = false)]
        public byte MessageType { get; set; }
        [Column(Name = "LinkedId", DbType = "Int32")]
        public Nullable<int> LinkedId { get; set; }
        [Column(Name = "DispatchType", DbType = "Byte", CanBeNull = false)]
        public byte DispatchType { get; set; }
        [Column(Name = "DispatchTime", DbType = "DateTime")]
    	private Nullable<System.DateTime> _dispatchTime;
    	public virtual Nullable<System.DateTime> DispatchTime 
    	{
    		get { return _dispatchTime; }
    		set 
    		{
    			if (value != null) {
    				if (value.Value.Kind == DateTimeKind.Unspecified) {
    					_dispatchTime = DateTime.SpecifyKind(value.Value, DateTimeKind.Utc);
    				} else {
    					_dispatchTime = value;
    				}
    			} else {
    				_dispatchTime = value;
    			}
    		}
    	}
        [Column(Name = "Status", DbType = "Byte", CanBeNull = false)]
        public byte Status { get; set; }
        [Column(Name = "LastUpdateUser", DbType = "String", CanBeNull = false)]
        public string LastUpdateUser { get; set; }
        [Column(Name = "LastUpdateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdateTime;
    	public virtual System.DateTime LastUpdateTime 
    	{
    		get { return _lastUpdateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdateTime = value;
    			}
    		}
    	}
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public bool IsActive { get; set; }
    
        private ICollection<MessageReceiver> _MessageReceiver;
        public virtual ICollection<MessageReceiver> MessageReceiver
        {
            get { return this._MessageReceiver ?? (this._MessageReceiver = new HashSet<MessageReceiver>()); }
            set { this._MessageReceiver = value; }
        }
    }
}
