//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class MessageReceiver
        : Entity
    {
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "MessageId", DbType = "Int32", CanBeNull = false)]
        public int MessageId { get; set; }
        [Column(Name = "UserId", DbType = "Int32", CanBeNull = false)]
        public int UserId { get; set; }
        [Column(Name = "ReceivedTime", DbType = "DateTime")]
    	private Nullable<System.DateTime> _receivedTime;
    	public virtual Nullable<System.DateTime> ReceivedTime 
    	{
    		get { return _receivedTime; }
    		set 
    		{
    			if (value != null) {
    				if (value.Value.Kind == DateTimeKind.Unspecified) {
    					_receivedTime = DateTime.SpecifyKind(value.Value, DateTimeKind.Utc);
    				} else {
    					_receivedTime = value;
    				}
    			} else {
    				_receivedTime = value;
    			}
    		}
    	}
        [Column(Name = "Status", DbType = "Byte", CanBeNull = false)]
        public byte Status { get; set; }
        [Column(Name = "LastUpdateUser", DbType = "String", CanBeNull = false)]
        public string LastUpdateUser { get; set; }
        [Column(Name = "LastUpdateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdateTime;
    	public virtual System.DateTime LastUpdateTime 
    	{
    		get { return _lastUpdateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdateTime = value;
    			}
    		}
    	}
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public bool IsActive { get; set; }
    
        public virtual MessageDispatch MessageDispatch { get; set; }
        public virtual User User { get; set; }
    }
}
