//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class Role
        : Entity
    {
        public Role()
        {
        }
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "Name", DbType = "String", CanBeNull = false)]
        public string Name { get; set; }
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public bool IsActive { get; set; }
        [Column(Name = "LastUpdateUser", DbType = "String", CanBeNull = false)]
        public string LastUpdateUser { get; set; }
        [Column(Name = "LastUpdateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdateTime;
    	public virtual System.DateTime LastUpdateTime 
    	{
    		get { return _lastUpdateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdateTime = value;
    			}
    		}
    	}
    
        private ICollection<RolePermission> _RolePermission;
        public virtual ICollection<RolePermission> RolePermission
        {
            get { return this._RolePermission ?? (this._RolePermission = new HashSet<RolePermission>()); }
            set { this._RolePermission = value; }
        }
        private ICollection<UserRole> _UserRole;
        public virtual ICollection<UserRole> UserRole
        {
            get { return this._UserRole ?? (this._UserRole = new HashSet<UserRole>()); }
            set { this._UserRole = value; }
        }
    }
}
