//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class SleemonExceptionLog
        : Entity
    {
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "Date", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _date;
    	public virtual System.DateTime Date 
    	{
    		get { return _date; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_date = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_date = value;
    			}
    		}
    	}
        [Column(Name = "Thread", DbType = "String", CanBeNull = false)]
        public string Thread { get; set; }
        [Column(Name = "Level", DbType = "String", CanBeNull = false)]
        public string Level { get; set; }
        [Column(Name = "Logger", DbType = "String", CanBeNull = false)]
        public string Logger { get; set; }
        [Column(Name = "Message", DbType = "String", CanBeNull = false)]
        public string Message { get; set; }
        [Column(Name = "Exception", DbType = "String")]
        public string Exception { get; set; }
    }
}
