//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class UserTraining
        : Entity
    {
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "UserUniqueId", DbType = "String", CanBeNull = false)]
        public string UserUniqueId { get; set; }
        [Column(Name = "TrainingId", DbType = "Int32", CanBeNull = false)]
        public int TrainingId { get; set; }
        [Column(Name = "JoinTime", DbType = "DateTime")]
    	private Nullable<System.DateTime> _joinTime;
    	public virtual Nullable<System.DateTime> JoinTime 
    	{
    		get { return _joinTime; }
    		set 
    		{
    			if (value != null) {
    				if (value.Value.Kind == DateTimeKind.Unspecified) {
    					_joinTime = DateTime.SpecifyKind(value.Value, DateTimeKind.Utc);
    				} else {
    					_joinTime = value;
    				}
    			} else {
    				_joinTime = value;
    			}
    		}
    	}
        [Column(Name = "JoinStatus", DbType = "Int32")]
        public Nullable<int> JoinStatus { get; set; }
        [Column(Name = "IsCheckInDone", DbType = "Boolean")]
        public Nullable<bool> IsCheckInDone { get; set; }
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public bool IsActive { get; set; }
    
        public virtual Training Training { get; set; }
    }
}
