//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class UserOrderShow
        : Entity
    {
        public UserOrderShow()
        {
        }
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "UserUniqueId", DbType = "String", CanBeNull = false)]
        public string UserUniqueId { get; set; }
        [Column(Name = "IsLegal", DbType = "Boolean", CanBeNull = false)]
        public bool IsLegal { get; set; }
        [Column(Name = "ShowTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _showTime;
    	public virtual System.DateTime ShowTime 
    	{
    		get { return _showTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_showTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_showTime = value;
    			}
    		}
    	}
        [Column(Name = "LastUpdateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdateTime;
    	public virtual System.DateTime LastUpdateTime 
    	{
    		get { return _lastUpdateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdateTime = value;
    			}
    		}
    	}
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public bool IsActive { get; set; }
    
        private ICollection<OrderShowFile> _OrderShowFile;
        public virtual ICollection<OrderShowFile> OrderShowFile
        {
            get { return this._OrderShowFile ?? (this._OrderShowFile = new HashSet<OrderShowFile>()); }
            set { this._OrderShowFile = value; }
        }
    }
}
