//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class UserTask
        : Entity
    {
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "UserUniqueId", DbType = "String", CanBeNull = false)]
        public string UserUniqueId { get; set; }
        [Column(Name = "TaskId", DbType = "Int32", CanBeNull = false)]
        public int TaskId { get; set; }
        [Column(Name = "CompleteTime", DbType = "DateTime")]
    	private Nullable<System.DateTime> _completeTime;
    	public virtual Nullable<System.DateTime> CompleteTime 
    	{
    		get { return _completeTime; }
    		set 
    		{
    			if (value != null) {
    				if (value.Value.Kind == DateTimeKind.Unspecified) {
    					_completeTime = DateTime.SpecifyKind(value.Value, DateTimeKind.Utc);
    				} else {
    					_completeTime = value;
    				}
    			} else {
    				_completeTime = value;
    			}
    		}
    	}
        [Column(Name = "Score", DbType = "Double")]
        public Nullable<double> Score { get; set; }
        [Column(Name = "Point", DbType = "Int32")]
        public Nullable<int> Point { get; set; }
        [Column(Name = "Status", DbType = "Byte", CanBeNull = false)]
        public byte Status { get; set; }
        [Column(Name = "AssignTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _assignTime;
    	public virtual System.DateTime AssignTime 
    	{
    		get { return _assignTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_assignTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_assignTime = value;
    			}
    		}
    	}
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public bool IsActive { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
