//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleemon.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    
    public partial class UserMoments
        : Entity
    {
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public int Id { get; set; }
        [Column(Name = "UserUniqueId", DbType = "String", CanBeNull = false)]
        public string UserUniqueId { get; set; }
        [Column(Name = "Moment", DbType = "String", CanBeNull = false)]
        public string Moment { get; set; }
        [Column(Name = "Category", DbType = "Byte", CanBeNull = false)]
        public byte Category { get; set; }
        [Column(Name = "RefId", DbType = "Int32")]
        public Nullable<int> RefId { get; set; }
        [Column(Name = "PostTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _postTime;
    	public virtual System.DateTime PostTime 
    	{
    		get { return _postTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_postTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_postTime = value;
    			}
    		}
    	}
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public bool IsActive { get; set; }
    }
}
